name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: macOS-12

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v --filter tinys3

  linuxbuild:
    name: Build and Test (Linux)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: make linux_build
    - name: Test
      run: make linux_test

  lint:
      name: SwiftLint
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Lint
          run: make lint
